### PR TITLE
Fix #178

### LINKED ISSUE #178: Coil fails to load image with a native crash on emulator
**Describe the bug**
A particular image is failing to load when using Coil.
The app crashes with a native crash.

Image causing this: https://d2lnr5mha7bycj.cloudfront.net/product-image/file/primary_2a461463-ca35-44b6-82b7-426375c8f70c.png

**Expected behavior**
The image should load and be displayed in the ImageView

**To Reproduce**
Load the above-mentioned image into an ImageView

**Version**
The issue is reproducible on the API 26 Emulator.

**Logs/Screenshots**
```2019-11-18 19:12:00.044 1723-1743/system_process E/memtrack: Couldn't load memtrack module
2019-11-18 19:12:15.027 2273-3221/com.google.android.gms E/ZappPhoneskyConn: Unable to bind to Phonesky
2019-11-18 19:12:15.069 1580-1955/? E/OMXNodeInstance: setConfig(0xe64a1080:google.mp3.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
2019-11-18 19:12:15.069 1580-1955/? E/OMXNodeInstance: getConfig(0xe64a1080:google.mp3.decoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2019-11-18 19:12:21.353 3957-5211/com.instacart.instashopper.v2.dev E/EGL_emulation: tid 5211: eglCreateImageKHR(1978): error 0x300c (EGL_BAD_PARAMETER)
2019-11-18 19:12:21.509 5921-5362/? A/google-breakpad: Microdump skipped (uninteresting)
2019-11-18 19:12:21.543 3957-5362/com.instacart.instashopper.v2.dev A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 5362 (DefaultDispatch)
2019-11-18 19:12:21.588 3957-5211/com.instacart.instashopper.v2.dev E/EGL_emulation: tid 5211: eglCreateImageKHR(1978): error 0x300c (EGL_BAD_PARAMETER)
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: Build fingerprint: 'Android/sdk_gphone_x86_64/generic_x86_64:8.0.0/OSR1.180418.019/5598391:userdebug/dev-keys'
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: Revision: '0'
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: ABI: 'x86_64'
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: pid: 3957, tid: 5362, name: DefaultDispatch  >>> com.instacart.instashopper.v2.dev <<<
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG: Cause: null pointer dereference
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     rax 00007eab42d243c0  rbx 0000000000000002  rcx 00007eab42d243c0  rdx 0000000070ce2340
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     rsi 0000000000000926  rdi ffffffffffffffe8
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     r8  0000000000000000  r9  00000000ffffffff  r10 00007eab40d50888  r11 0000000000000246
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     r12 0000000000000000  r13 0000000000000000  r14 0000000000000000  r15 00007eab42c93280
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     cs  0000000000000033  ss  000000000000002b
2019-11-18 19:12:21.630 5925-5925/? A/DEBUG:     rip 00007eab659f3891  rbp 0000000000000000  rsp 00007eab367f1480  eflags 0000000000010206
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG: backtrace:
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #00 pc 0000000000130891  /system/lib64/libandroid_runtime.so (_ZN7android6bitmap12createBitmapEP7_JNIEnvPNS_6BitmapEiP11_jbyteArrayP8_jobjecti+81)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #01 pc 0000000000136bc2  /system/lib64/libandroid_runtime.so (_ZL8doDecodeP7_JNIEnvP18SkStreamRewindableP8_jobjectS4_+4850)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #02 pc 0000000000ae852b  /system/framework/x86_64/boot-framework.oat (offset 0x5e6000) (android.graphics.BitmapFactory.nativeDecodeStream [DEDUPED]+331)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #03 pc 00000000005c9f56  /system/lib64/libart.so (art_quick_invoke_static_stub+806)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #04 pc 000000000014366d  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+253)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #05 pc 000000000030c3fa  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+330)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #06 pc 000000000030621c  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+828)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #07 pc 00000000005b0cb1  /system/lib64/libart.so (MterpInvokeStatic+497)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #08 pc 00000000005b9e19  /system/lib64/libart.so (artMterpAsmInstructionStart+14489)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #09 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #10 pc 00000000002eb004  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #11 pc 0000000000306204  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+804)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #12 pc 00000000005b0cb1  /system/lib64/libart.so (MterpInvokeStatic+497)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #13 pc 00000000005b9e19  /system/lib64/libart.so (artMterpAsmInstructionStart+14489)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #14 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #15 pc 00000000002eb004  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #16 pc 0000000000306204  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+804)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #17 pc 00000000005b0cb1  /system/lib64/libart.so (MterpInvokeStatic+497)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #18 pc 00000000005b9e19  /system/lib64/libart.so (artMterpAsmInstructionStart+14489)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #19 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #20 pc 00000000002eb004  /system/lib64/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+212)
2019-11-18 19:12:21.797 5925-5925/? A/DEBUG:     #21 pc 0000000000307299  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb1ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+825)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #22 pc 00000000005b22e3  /system/lib64/libart.so (MterpInvokeInterfaceRange+1731)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #23 pc 00000000005ba199  /system/lib64/libart.so (artMterpAsmInstructionStart+15385)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #24 pc 00000000002e477a  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+474)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #25 pc 00000000005a1705  /system/lib64/libart.so (artQuickToInterpreterBridge+1365)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #26 pc 00000000005d421c  /system/lib64/libart.so (art_quick_to_interpreter_bridge+140)
2019-11-18 19:12:21.798 5925-5925/? A/DEBUG:     #27 pc 000000000011a782  /dev/ashmem/dalvik-jit-code-cache (deleted)
2019-11-18 19:12:23.035 1584-1584/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_00
2019-11-18 19:12:23.072 1436-2069/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property```

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

File: coil-base/src/main/java/coil/memory/HardwareBitmapService.kt [hunk 1]
```diff
@@ -20,18 +22,30 @@ internal sealed class HardwareBitmapService {
...
 
-    override fun allowHardware(size: Size) = allowHardware
+    override fun allowHardware(size: Size, target: Target?) = allowHardware
+}
+
+/* Validates that the view is ViewTarget and checks if its hardware accelerated */
+private object ValidateHardwareBitmapService : HardwareBitmapService() {
+
+    override fun allowHardware(size: Size, target: Target?): Boolean {
+        if (target != null && target is ViewTarget<*>) {
```
Comment (colinrtwhite) [inline coil-base/src/main/java/coil/memory/HardwareBitmapService.kt]: Let's move this check to `Request.isConfigValidForHardware` and keep `ImmutableHardwareBitmapService` as is. `HardwareBitmapService` is supposed to handle device-specific and file system limitations for hardware bitmaps.

File: coil-base/src/main/java/coil/memory/RequestService.kt [hunk 2]
```diff
@@ -145,10 +147,14 @@ internal class RequestService {
...
-        if (bitmapConfig != Bitmap.Config.HARDWARE) return true
-        return allowHardware && hardwareBitmapService.allowHardware(size)
+    private fun Request.isConfigValidForHardware(size: Size, target: Target?): Boolean {
+        if (SDK_INT >= O) {
+            if (bitmapConfig != Bitmap.Config.HARDWARE) {
+                return true
+            }
+        }
+
+        return !allowHardware || hardwareBitmapService.allowHardware(size, target)
```
Comment (colinrtwhite) [inline coil-base/src/main/java/coil/memory/RequestService.kt]: Can you keep the existing formatting when you add the extra check? Thanks!

Comment (mario) [reply coil-base/src/main/java/coil/memory/RequestService.kt]: I can try :)

**Comment by mario** [comment]
@colinrtwhite pushed. Happy to make further changes if I missed something.

File: coil-base/src/main/java/coil/memory/RequestService.kt [hunk 3]
```diff
@@ -145,10 +147,10 @@ internal class RequestService {
         return transformations.isEmpty() || Transformation.VALID_CONFIGS.contains(bitmapConfig)
     }
 
-    private fun Request.isConfigValidForHardware(size: Size): Boolean {
+    private fun Request.isConfigValidForHardware(size: Size, target: Target?): Boolean {
         if (SDK_INT < O) return true
         if (bitmapConfig != Bitmap.Config.HARDWARE) return true
-        return allowHardware && hardwareBitmapService.allowHardware(size)
+        return allowHardware && hardwareBitmapService.allowHardware(size) && (target !is ViewTarget<*> || target.view.isHardwareAccelerated)
```
Comment (colinrtwhite) [inline coil-base/src/main/java/coil/memory/RequestService.kt]: We should check `hardwareBitmapService.allowHardware(size)` last since it can be expensive. Also let's add this target check on a separate line.

File: coil-base/src/main/java/coil/memory/RequestService.kt [hunk 4]
```diff
@@ -145,10 +147,10 @@ internal class RequestService {
         return transformations.isEmpty() || Transformation.VALID_CONFIGS.contains(bitmapConfig)
     }
 
-    private fun Request.isConfigValidForHardware(size: Size): Boolean {
+    private fun Request.isConfigValidForHardware(size: Size, target: Target?): Boolean {
```
Comment (colinrtwhite) [inline coil-base/src/main/java/coil/memory/RequestService.kt]: `target` is already part of the `Request` receiver so we don't need to pass it in.

**Comment by mario** [comment]
Thanks for the patience.
