### PR TITLE
Fix handling contact display photos.

### LINKED ISSUE #136: java.io.FileNotFoundException: No photo file found for ID 0
Hi, I am trying Coil for loading Contact photos on Android. While my own sample implementation can load bitmap from (i.e) content://com.android.contacts/contacts/129/display_photo, I get  `java.io.FileNotFoundException: No photo file found for ID 0` error when i use Coil.

Full log:
`RealImageLoader: 🚨 Failed - content://com.android.contacts/contacts/129/display_photo - java.io.FileNotFoundException: No photo file found for ID 0
2019-10-03 21:53:27.747 31928-31928/com.nll.cb E/RealImageLoader: java.io.FileNotFoundException: No photo file found for ID 0
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1465)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1302)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1022)
        at a.m.c.a(ContentUriFetcher.kt:26)
        at a.m.c.a(ContentUriFetcher.kt:13)
        at a.g.invokeSuspend(RealImageLoader.kt:329)
        at e.v.i.a.a.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.x0.run(Dispatched.kt:241)
        at kotlinx.coroutines.y2.a.a(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.y2.a.a(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.y2.a$b.run(CoroutineScheduler.kt:740)`

Here is my code that loads contact photo just fine in the same app:

`Uri displayPhotoUri = Uri.withAppendedPath(contactUri, ContactsContract.Contacts.Photo.DISPLAY_PHOTO);
           
            try {
                AssetFileDescriptor fd = cr.openAssetFileDescriptor(displayPhotoUri, "r");
             
                FileInputStream stream = fd.createInputStream();

                if (stream != null) {
                   
                    return stream;
                }
            } catch (IOException e) {
             

            }`

### PR DESCRIPTION
**Pull request by colinrtwhite**
Fixes #136.

### CODE REVIEW

File: coil-base/src/main/java/coil/fetch/ContentUriFetcher.kt [hunk 1]
```diff
@@ -22,10 +26,25 @@ internal class ContentUriFetcher(private val context: Context) : Fetcher<Uri> {
         size: Size,
         options: Options
     ): FetchResult {
+        val inputStream = if (isContactPhotoUri(data)) {
```
Comment (colinrtwhite) [inline coil-base/src/main/java/coil/fetch/ContentUriFetcher.kt]: Opting to keep this logic as part of the `ContentUriFetcher`. I'd like to avoid adding a new `Fetcher` class for this special case.
