### PR TITLE
Fix HttpFetcher blocking forever if called from the main thread.

### LINKED ISSUE #615: Calling execute() on the main thread freezes the app
**Describe the bug**

Attempts to run execute() on the main thread cause freezes the app.

**Expected behavior**

I expect to be able to run execute() on the main thread (even though yes, I know this is not good practice).

**To Reproduce**

Try to call `execute()` inside of `runBlocking {}` while on the main thread.

Here's a small sample:

```
class MainActivity : AppCompatActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val imageLoader = ImageLoader.Builder(this)
      .build()

    Log.i("test", "start")

    runBlocking {
      imageLoader.execute(
        ImageRequest.Builder(this@MainActivity)
          .data(R.drawable.image)
          .build()
      )
    }

    Log.i("test", "end") // Never prints
  }
}
```

**Version**

Coil 1.1.0.

### PR DESCRIPTION
**Pull request by colinrtwhite**
Fixes #615.

Fixes `HttpFetcher` blocking forever if called from the main thread.

- Requests that don't explicitly disable reading from the network using `ImageRequest.networkCachePolicy(CachePolicy.DISABLED)` will fail due to a `NetworkOnMainThreadException`.
- Requests that disable reading from the network and only read from the disk cache will work as expected.

### CODE REVIEW

File: coil-base/src/test/java/coil/fetch/HttpFetcherTest.kt [hunk 1]
```diff
@@ -51,7 +55,7 @@ class HttpFetcherTest {
         context = ApplicationProvider.getApplicationContext()
         mainDispatcher = createTestMainDispatcher()
         server = createMockWebServer(context, "normal.jpg")
-        cache = Cache(File("build/cache"), 1024).apply { evictAll() }
+        cache = Cache(File("build/cache"), Long.MAX_VALUE).apply { evictAll() }
```
Comment (Jawnnypoo) [inline coil-base/src/test/java/coil/fetch/HttpFetcherTest.kt:58]: Is this change okay?

**Review by Jawnnypoo — APPROVED** [review]

File: coil-base/src/test/java/coil/fetch/HttpFetcherTest.kt (hunk 1 above)
Comment (colinrtwhite) [reply coil-base/src/test/java/coil/fetch/HttpFetcherTest.kt:58]: Yep, the cache is evicted at the end of the test.
